### ISSUE TITLE
Kibana diag improvements for prepackaged, stats, task health and new alerts health APIs

### ISSUE THREAD

**Issue by kostasb** [elastic/support-diagnostics#479] opened 2021-04-14 07:34 UTC
1) The `/api/detection_engine/prepackaged` Kibana API returns HTTP 404 with 7.11 and 7.12. We may want to remove this call from the diag tool

```
kibana_detection_engine_signals:
  versions:
    "> 7.10.0": "/api/detection_engine/prepackaged"
```

2) For the stats endpoint it is preferrably to retrieve the extended version which is much more verbose.
```
kibana_stats:
  versions:
    ">= 6.5.0": "/api/stats"
```

instead use: `/api/stats?extended=true`

3) The task manager health api is named "kibana_task_manager_help" in the diag tool, which generates output file "kibana_task_manager_help.json", it should better be "health" instead of "help" to align with the API call

```
kibana_task_manager_help:
  versions:
    ">= 7.11.0": "/api/task_manager/_health"
```

4) As of 7.11 there is a new Alert Framework Health API https://www.elastic.co/guide/en/kibana/current/alerts-api-health.html

Can we add this new API, i.e.:
```
kibana_alerts_health:
  versions:
    ">= 7.11.0": "/api/alerts/_health"
```

@CamiloSierraH what do you think?

**Comment by CamiloSierraH** [comment] 2021-04-19 17:50
Hey @kostasb and @danleerunk I will work on this now, I will submit a new PR asap!

**Comment by CamiloSierraH** [comment] 2021-04-20 16:52
I finished the first 3 changes.
The last one is interesting, by default only get the data for the default space, if the customer have multiple spaces, we will not collect all the information, I will do a code and review the other queries we have to be sure that we collect not only the data in default space, but in all the spaces.

```
GET <kibana host>:<port>/api/alerting/_health

GET <kibana host>:<port>/s/<space_id>/api/alerting/_health
```

**Comment by CamiloSierraH** [comment] 2021-04-20 23:44
I need to test it first but the code is here: https://github.com/CamiloSierraH/support-diagnostics/commit/8473f39e37aec9c366d3c9434942d3dcb43cce65

I updated all the kibana APIs (alerts, actions, detection_engine), so now we are collecting all the spaces data.
For the new query `kibana_alerts_health` we do the same, and we collect all the spaces data!

Hey @kostasb my friend if you want to test it you can see here the new jar https://drive.google.com/file/d/1LGq990SU1loTZj_bMuInyXEcfqV78eTU/view?usp=sharing

I need to run some test with kibana in remote and locat before push the PR, but I will push it tomorrow morning!

**Comment by CamiloSierraH** [comment] 2021-04-21 17:56
Ok the PR was create here: https://github.com/elastic/support-diagnostics/pull/483

**Comment by kostasb** [comment] 2021-04-22 17:07
Tested the 8.1.5 version provided by @CamiloSierraH on slack, all API outputs look good. Thanks Camilo!


![image](https://user-images.githubusercontent.com/15780449/115755746-59b70f80-a3a6-11eb-9e72-56b2b0c353c9.png)

**Comment by 111andre111** [comment] 2021-04-22 20:04
Confirmed from my side as well:

I have some additional APIs and would like to know if I should open a separate issue for them?
Forgive if I had a duplicate, that from a collection that I made some time ago.

Alerts/Actions
https://localhost:5601/api/actions/list_action_types
https://localhost:5601/api/alerts/_aggregate?default_search_operator=AND
https://localhost:5601/api/alerts/_health
https://localhost:5601/api/alerts/list_alert_types
https://localhost:5601/api/triggers_actions_ui/_health

Saved Objects/Spaces
https://localhost:5601/api/kibana/management/saved_objects/_allowed_types
https://localhost:5601/api/spaces/space?include_authorized_purposes=true

Detection
https://localhost:5601/api/detection_engine/privileges
https://localhost:5601/api/lists/privileges
https://localhost:5601/api/security/role
https://localhost:5601/internal/security/_check_role_mapping_features
https://localhost:5601/internal/security/api_key/privileges
https://localhost:5601/internal/security/me

Endpoint/Fleet
https://localhost:5601/api/endpoint/metadata
https://localhost:5601/api/endpoint/trusted_apps?page=1&per_page=1
https://localhost:5601/api/fleet/check-permissions
https://localhost:5601/api/fleet/package_policies?perPage=50&page=1&kuery=ingest-package-policies.package.name%3A%20endpoint
https://localhost:5601/api/infra/log_source_configurations/default/status

Tags
https://localhost:5601/api/cases/tags
https://localhost:5601/api/detection_engine/tags
https://localhost:5601/api/saved_objects_tagging/tags

detections/cases
https://localhost:5601/api/cases/reporters
https://localhost:5601/api/detection_engine/index
https://localhost:5601/api/detection_engine/rules/_find_statuses
https://localhost:5601/api/detection_engine/rules/prepackaged
https://localhost:5601/api/detection_engine/rules/prepackaged/_status
https://localhost:5601/api/reporting/jobs/list?page=0

ML capabilities
https://localhost:5601/api/ml/data_frame/analytics
https://localhost:5601/api/ml/data_frame/analytics/_stats
https://localhost:5601/api/ml/jobs/jobs_summary
https://localhost:5601/api/ml/ml_capabilities
https://localhost:5601/api/ml/modules/get_module/
https://localhost:5601/api/ml/saved_objects/jobs_spaces
https://localhost:5601/api/ml/saved_objects/sync?simulate=true

Watcher
https://localhost:5601/api/watcher/watches

**Comment by CamiloSierraH** [comment] 2021-04-24 00:06
The list is great Andre!!! not even the dev team or doc team has such complete list!!!

I have created a new case to review and prioritize the APIs we will add.

**Comment by cybersecdiva** [comment] 2021-08-11 17:37
I synced with @spong and I have synced on this and he will work on devising detection APIs and other items that we can for troubleshooting

**Comment by cybersecdiva** [comment] 2021-08-13 20:10
For reference the Slack thread in **#sdh-security**  channel that @spong initiated for contributions from team on detection APIs and other items: https://elastic.slack.com/archives/CUEC7HAKD/p1628721254011800

Thank you @spong  for your diligence and proactiveness :elasticheart: ⭐ ⭐ ⭐ ⭐ ⭐

**Comment by peluja1012** [comment] 2022-01-12 17:26
Hello @kostasb, do you know if there have been any recent updates on getting these improvements added? The data we would get with these changes would improve our SDH response time.

**Comment by kostasb** [comment] 2022-01-12 18:11
I will defer to @CamiloSierraH who, last time I was updated on this topic, was developing the Kibana API diagnostics. Also @111andre111 might know more?

**Comment by 111andre111** [comment] 2022-01-19 00:07
For documentation, I reached out to Pedro to find out the driver of his question.

**Comment by stefnestor** [comment] 2022-07-23 18:52
Circling back to https://github.com/elastic/support-diagnostics/issues/479#issuecomment-825148583: 

From offline discussions we'd determined that many of these `types` endpoints are per version and could be pulled separate from a user diagnostic to avoid weighing down already-strained clusters.

@111andre111 will you please sanity check that AFAICT

- [x] "Alerts/Actions": we've implemented all expected long-term "Alerts/Actions" (aka. not `alerts/_health` or `triggers_actions_ui/_health`)
- [x] "Saved Objects/Spaces": I added in spaces [1]
- [ ] "Detections"/"Detections/Cases": 
    - Security-related: I implemented `/internal/security/me` in [1] but can't tell (related to use case, I get the technical differences 🙂 ) if these others are just the Kibana-side of the Elasticsearch diag we already pull: [`/api/lists/privileges`, `/api/security/role`, `/internal/security/_check_role_mapping_features`, `/internal/security/api_key/privileges`]
    - SIEM-related: AFAICT [`[/api/detection_engine/index](https://localhost:5601/api/detection_engine/index)`,`/api/detection_engine/rules/prepackaged`,`/api/detection_engine/rules/_find_statuses`] just returns an aggregated/simplified view of `/api/detection_engine/rules/_find`. I suspect but can't confirm these last two may be beneficial additions still: [`/api/detection_engine/rules/prepackaged/_status`, `/api/cases/reporters`]?
- [ ]  "Tags": I'm not sure I know the context to justify this as requested in [2]. Usually, I can answer all tags questions by having a user forward a HAR log.
- [ ] Split out "Reporting": `/api/reporting/jobs/list?page=0` is gold, will need to confirm no PII
- [ ] "Fleet": we've not implemented any of this but Fleet questions are exploding. Are we able to add these endpoints even though Fleet is now GA but [its API is Experimental](https://github.com/elastic/kibana/tree/main/x-pack/plugins/fleet/common/openapi)?
 -  [ ] "ML capabilities": When I talked to ML Dev, they were careful to set expectations that we expect to pull this data through the ES diag (since ES-level feature). Do any of these endpoints offer supplementary details not captured via the ES diag?
- [ ] "Watcher": Is this current [Watcher data pull](https://github.com/stefnestor/support-diagnostics/tree/main/) sufficient from the ES diag? (It looks like a reformatting to me, but I could be missing something.)

[1] https://github.com/elastic/support-diagnostics/pull/580
[2] https://github.com/elastic/support-diagnostics/issues/484#issuecomment-829296142

**Comment by 111andre111** [comment] 2023-06-30 20:41
We can close this issue.

Most of the work here is done
  Done - remove /api/detection_engine/prepackaged
  Done - kibana_task_manager_help to kibana_task_manager_health
  Done - add /api/alerts/_health
  Done - /internal/security/me
  Done - /api/security/role

For now I would not add `/api/detection_engine/rules/prepackaged/_status` as it seems this API is not very performant

For list priviliges I already opened now a pr:
https://github.com/elastic/support-diagnostics/pull/645

**Closed** 2023-06-30 20:44 UTC
Labels: diagnostic
