### ISSUE TITLE
Monitoring data import not working to ESS

### ISSUE THREAD

**Issue by toby-sutor** [elastic/support-diagnostics#457] opened 2020-12-28 10:39 UTC
Reopening as I can still reproduce this (ref. https://github.com/elastic/support-diagnostics/issues/450 and https://github.com/elastic/support-diagnostics/issues/350)

**Steps to reproduce**:
1. Create an ESS deployment (7.10.1 on GCP Belgium, highIO with a single 4GB node).
2. Enable Stack Monitoring (same behavior with skipping this step)
2. Download the Support Diagnostics from https://github.com/elastic/support-diagnostics/releases/tag/8.1.2
3. Run it like this (on a Mac with Firewall enabled/disabled):
`./import-monitoring.sh -i ../monitoring-export-20201224-123.zip --host REDACTED.europe-west1.gcp.cloud.es.io -u elastic -p --ssl --port 9243`
Returns:
````
$ ./import-monitoring.sh -i ../monitoring-export-20201224-123.zip --host REDACTED.europe-west1.gcp.cloud.es.io -u elastic -p --ssl --port 9243
Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
2020-12-28 11:19:24,179 main ERROR Unable to locate appender "diag" for logger config "root"
Processing diagnosticInputs...
Elasticsearch user password: ***************
Deleted directory: /Users/toby/support-diagnostics-8.1.2/monitoring-export.
Creating temporary directory /Users/toby/support-diagnostics-8.1.2/monitoring-export
Configuring log file.
Diagnostic logger reconfigured for inclusion into archive
Extract completed successfully!
Processing: metricbeat-cpu.json
Indexing document batch 0 to 500
Error processing JSON event for {}.
java.lang.RuntimeException: Broken pipe (Write failed)
	at com.elastic.support.rest.RestClient.execRequest(RestClient.java:79) ~[support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.rest.RestClient.execPost(RestClient.java:91) ~[support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.monitoring.MonitoringImportProcessor.writeBatch(MonitoringImportProcessor.java:145) ~[support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.monitoring.MonitoringImportProcessor.process(MonitoringImportProcessor.java:112) [support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.monitoring.MonitoringImportProcessor.exec(MonitoringImportProcessor.java:54) [support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.monitoring.MonitoringImportService.execImport(MonitoringImportService.java:55) [support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.monitoring.MonitoringImportApp.main(MonitoringImportApp.java:37) [support-diagnostics-8.1.2.jar:8.1.2]
0 events written from metricbeat-cpu.json
Processing: metricbeat-diskio.json
Indexing document batch 0 to 500
Error processing JSON event for {}.
java.lang.RuntimeException: Broken pipe (Write failed)
````

From the logs:
````
11:29:47.618 [main] INFO  com.elastic.support.BaseService - Diagnostic logger reconfigured for inclusion into archive
11:30:42.406 [main] ERROR com.elastic.support.rest.RestClient - Unexpected Execution Error
javax.net.ssl.SSLException: Broken pipe (Write failed)
	at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:320) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:263) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:258) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1016) ~[?:?]
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124) ~[httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:160) ~[httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113) ~[httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:120) ~[httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.entity.StringEntity.writeTo(StringEntity.java:167) ~[httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156) ~[httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238) ~[httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123) ~[httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.10.jar:4.5.10]
	at com.elastic.support.rest.RestClient.execRequest(RestClient.java:73) [support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.rest.RestClient.execPost(RestClient.java:91) [support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.monitoring.MonitoringImportProcessor.checkForExtractTemplates(MonitoringImportProcessor.java:166) [support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.monitoring.MonitoringImportProcessor.<init>(MonitoringImportProcessor.java:43) [support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.monitoring.MonitoringImportService.execImport(MonitoringImportService.java:54) [support-diagnostics-8.1.2.jar:8.1.2]
	at com.elastic.support.monitoring.MonitoringImportApp.main(MonitoringImportApp.java:37) [support-diagnostics-8.1.2.jar:8.1.2]
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:?]
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110) ~[?:?]
		at java.net.SocketOutputStream.write(SocketOutputStream.java:150) ~[?:?]
		at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81) ~[?:?]
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:351) ~[?:?]
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:263) ~[?:?]
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:258) ~[?:?]
		at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1016) ~[?:?]
		at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124) ~[httpcore-4.4.12.jar:4.4.12]
		at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:160) ~[httpcore-4.4.12.jar:4.4.12]
		at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113) ~[httpcore-4.4.12.jar:4.4.12]
		at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:120) ~[httpcore-4.4.12.jar:4.4.12]
		at org.apache.http.entity.StringEntity.writeTo(StringEntity.java:167) ~[httpcore-4.4.12.jar:4.4.12]
		at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156) ~[httpcore-4.4.12.jar:4.4.12]
		at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152) ~[httpclient-4.5.10.jar:4.5.10]
		at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238) ~[httpcore-4.4.12.jar:4.4.12]
		at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123) ~[httpcore-4.4.12.jar:4.4.12]
		at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.10.jar:4.5.10]
		at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar:4.5.10]
		at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar:4.5.10]
		at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar:4.5.10]
		at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar:4.5.10]
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.10.jar:4.5.10]
		at com.elastic.support.rest.RestClient.execRequest(RestClient.java:73) [support-diagnostics-8.1.2.jar:8.1.2]
		at com.elastic.support.rest.RestClient.execPost(RestClient.java:91) [support-diagnostics-8.1.2.jar:8.1.2]
		at com.elastic.support.monitoring.MonitoringImportProcessor.checkForExtractTemplates(MonitoringImportProcessor.java:166) [support-diagnostics-8.1.2.jar:8.1.2]
		at com.elastic.support.monitoring.MonitoringImportProcessor.<init>(MonitoringImportProcessor.java:43) [support-diagnostics-8.1.2.jar:8.1.2]
		at com.elastic.support.monitoring.MonitoringImportService.execImport(MonitoringImportService.java:54) [support-diagnostics-8.1.2.jar:8.1.2]
		at com.elastic.support.monitoring.MonitoringImportApp.main(MonitoringImportApp.java:37) [support-diagnostics-8.1.2.jar:8.1.2]
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:?]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110) ~[?:?]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:150) ~[?:?]
	at sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:320) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1011) ~[?:?]
	... 21 more
11:30:42.411 [main] ERROR com.elastic.support.monitoring.MonitoringImportProcessor - Issue checking template metricbeat-system-diag
java.lang.RuntimeException: Broken pipe (Write failed)
````

**Comment by nemonster** [comment] 2020-12-31 14:02
The trace shows that you are trying to do this with the 8.1.2 version. That won't work. If you want the fixes you'll need to use the 9.0.0 pre-release.

**Comment by toby-sutor** [comment] 2021-01-05 08:34
> The trace shows that you are trying to do this with the 8.1.2 version. That won't work. If you want the fixes you'll need to use the 9.0.0 pre-release.

Thank you for the clarification, it was not obvious from the other issues that this is only supposed to be fixed in the 9.x branch.

**Comment by PhaedrusTheGreek** [comment] 2021-01-07 15:39
@toby-sutor can you verify the fix is working in 9?

**Comment by chason** [comment] 2021-01-28 01:32
Closing due to lack of reproducibility

**Closed** 2021-01-28 01:33 UTC
Labels: [zube]: Needs Grooming

**Comment by predogma** [comment] 2021-02-17 20:49
Just reference examples syntax for export/import monitoring data using v9.0.0 pre-release (not same as 8.1.x)

```
./export-monitoring.sh --help
## get ids of clusters monitored data avail for
./export-monitoring.sh -list -url https://2d------------d0e3.eastus2.azure.elastic-cloud.com:9243

## export pass in id of cluster monitoring data, add -interval otherwise default to 6 (hours max 12)
./export-monitoring.sh -output <path> -url https://2d-----------0e3.eastus2.azure.elastic-cloud.com:9243 -id <clusterid> 

./import-monitoring.sh --help
## destination needs monitoring enabled for import/visualizations
./import-monitoring.sh -url https://31------------d736b.eastus2.azure.elastic-cloud.com:9243 -input monitoring-export-20210217-152248.zip -clustername <overridename>

```
