### ISSUE TITLE
Error when password has the character !

### ISSUE THREAD

**Issue by immavalls** [elastic/support-diagnostics#390] opened 2020-04-01 05:39 UTC
### Problem

It seems that diagnostics will fail if the password has a `!` character.

### Steps to reproduce

```
./diagnostics.sh --type api -u another --password --ssl --noVerify --bypassDiagVerify --host my-host  --port 9200
```

Password: `changeme!0`

The collected password is thus incorrect and we get:

```
Using /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Processing diagnosticInputs...
Elasticsearch user password: *********
[ERROR] Could not expand event
java.lang.IllegalArgumentException: !0: event not found
        at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:855)
        at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:715)
        at jline.console.ConsoleReader.accept(ConsoleReader.java:2025)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2698)
        at org.beryx.textio.jline.JLineTextTerminal.read(JLineTextTerminal.java:240)
        at org.beryx.textio.InputReader.readWithPrompt(InputReader.java:460)
        at org.beryx.textio.InputReader.lambda$read$3(InputReader.java:405)
        at org.beryx.textio.TextTerminal.applyWithPropertiesConfigurator(TextTerminal.java:243)
        at org.beryx.textio.InputReader.executeWithTerminal(InputReader.java:484)
        at org.beryx.textio.InputReader.read(InputReader.java:403)
        at org.beryx.textio.InputReader.read(InputReader.java:391)
        at com.elastic.support.rest.ElasticRestClientInputs.parseInputs(ElasticRestClientInputs.java:111)
        at com.elastic.support.diagnostics.DiagnosticInputs.parseInputs(DiagnosticInputs.java:221)
        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:26)


Creating temp directory: /tmp/api-diagnostics
Configuring log file.
Getting Elasticsearch Version.
Could not retrieve the Elasticsearch version - unable to continue. Status: 401  Reason: Authentication failure. Invalid login credentials.
Closing logger.
Archiving diagnostic results.
Archive: /tmp/api-diagnostics-20200401-073324.tar.gz was created
```

### Workaround

The workaround is to ask the customer to use a user that does not have a `!` in the password.

**Comment by nemonster** [comment] 2020-04-01 23:15
I just went through checking this, and it's not quite what is described. Using a standard command line execution, the exclamation point works fine. The stack trace looked odd though, and after running in interactive mode it appears that the exclamation point does cause an issue there. I'll need to take a deeper look at this, but in the short term the workaround is not to avoid the ! character - you can use them, just not run in interactive mode. Use the command line version where you send in all the non-password parameters but enter the password at the prompt.  That will work.

**Comment by nemonster** [comment] 2020-04-02 01:27
I've isolated the issue. Limitation of the console, but there's a code workaround I can implement so it will be addressed in the next minor release.

**Comment by maulinglawns** [comment] 2020-04-03 10:27
> Use the command line version where you send in all the non-password parameters but enter the password at the prompt. That will work.

Could you please explain this. Preferably with an example. Because I cannot get it to work!

**Comment by 111andre111** [comment] 2020-04-03 13:32
The real workaround that I at least found out is you could use parameter `--passwordText` and escape the exclamation marks like that:
`./diagnostics.sh --bypassDiagVerify --user elastic --passwordText 12345\!\!\!\!\!12345`

This has something to do with history expansion which equals in bash to the SHELLOPTS parameter part `histexpand` and in zsh I think it is `expand-history`.
But if you have a programmatic way to solve that the better.

**Comment by maulinglawns** [comment] 2020-04-04 10:49
> The real workaround that I at least found out is you could use parameter `--passwordText` and escape the exclamation marks like that:
> `./diagnostics.sh --bypassDiagVerify --user elastic --passwordText 12345\!\!\!\!\!12345`
@111andre111 Thank you. This variant works. With the obvious caveat that the password is saved in the shell history, so you have to remember that particular entry.

**Comment by nemonster** [comment] 2020-04-06 14:34
@maulinglawns Actually, if you use the --passwordText option you shouldn't even have the issue. So you shouldn't have to even apply those characters for the call above. The issue is in the Jline library I use to get the text input, and that's being bypassed in this case.

**Closed** 2020-04-06 14:51 UTC
Labels: [zube]: Sprint Queue, bug

**Comment by maulinglawns** [comment] 2020-04-16 11:05
@nemonster Thanks. I just tried the latest release, and it works as expected.
