### ISSUE TITLE
If diagnostics fails, fail with an error

### ISSUE THREAD

**Issue by robin13** [elastic/support-diagnostics#79] opened 2016-01-27 15:17 UTC
If I run diagnostics.sh with incorrect parameters (e.g. invalid host), it completes with something like:

```
Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Prompt for a password?  No password value required, only the option. Hidden from the command line on entry.: 
Getting Network Interface Information - this may take some time...
Run 1 of 1 completed.
```

No file created, no error posted... it looks as if it did something, but nothing happened.  This confused me, and will surely confuse others.

**Comment by nemonster** [comment] 2016-01-27 15:30
There should be an error in the log file - by default, unless you change the logging configuration it will be in <user dir>/elasticsearch-diagnostics.  Think this is in the troubleshooting section of the KB, but I'm make sure there's also a section in the readme.  The question here would be, exactly *which* invalid parameters were used.  Host and ???  and what were those values?

**Comment by robin13** [comment] 2016-01-29 08:49
```
rclarke@es-rclarke:support-diagnostics-2.0.2$ ./diagnostics.sh --ssl --host node-eu-west-1.foundcluster.com:9243 -u username -p
Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Prompt for a password?  No password value required, only the option. Hidden from the command line on entry.: <invalid password entered>
Getting Network Interface Information - this may take some time...
Run 1 of 1 completed.
```

**Comment by robin13** [comment] 2016-01-29 09:53
Ahh... so I found the logs now which do note `invalid login credentials`, but 
1. I would not have know that logs are being written to a file...
2. I would not have known where to find the file...
3. If an error occurs, I'd expect at least a summary of the error to be printed to screen, possibly noting the location of the log file and the fact that more information may be available there.

**Comment by jakommo** [comment] 2016-02-02 21:56
:+1:  on an error message. Had at least two customers accidentally  passing a wrong param and wonder why no diag was created.

**Comment by nemonster** [comment] 2016-02-02 22:00
Which param?  It has to be fairly severe for it not to create any diag at all?

**Comment by jakommo** [comment] 2016-02-03 08:08
In one case this was caused by calling the script with `-s` against a cluster that doesn't use ssl.

```
./diagnostics.sh --host localhost --port 9200 -o test -s
Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Getting Network Interface Information - this may take some time...
Run 1 of 1 completed.
```

It would be nice for the user to easily spot that it fails

**Comment by nemonster** [comment] 2017-03-31 19:05
No easy way to verify this.

**Comment by robin13** [comment] 2017-04-03 07:17
@nemonster 
But would this be possible?

> If an error occurs, I'd expect at least a summary of the error to be printed to screen, possibly noting the location of the log file and the fact that more information may be available there.

I understand it may be difficult to determine if SSL failed etc., but the main issue here is failing silently with errors written to a log file whose existence the user is probably unaware.

**Closed** 2018-12-13 19:54 UTC
Labels: [zube]: Unsorted, wontfix
