### ISSUE TITLE
Sanitising slowlog 

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/support-diagnostics#410] opened 2020-05-14 06:31 UTC
slowlog usually contains sensitive information like the actual query people are running, but they don't seem to be processed by `scrub.sh`

Would it be possible to sanitising slowlog and removing the request body?

**Comment by nemonster** [comment] 2020-05-18 15:03
I've looked at the output in Slack and from what I can see, the files are being scanned. So given the reluctance to share any actual content, I think you and the customer need to do some further investigation, since if the file is being scanned and nothing is happening it generally means that the definition of the token to be scrubbed is not matching with the actual content. And I can't do anything about that without some sort of reproducible sample.

So I'd have a couple of questions right off that I think you probably need to look at.

 * Do some token definitions get scrubbed but not others?
* Do tokens in other files with exactly the same values get scrubbed?
* What is the character set in the files being scanned? 

And from this point, I am going to have to insist that any further discussion or work be conducted on the latest version of the diagnostic. I am OK with moving back a few versions, as far back as 7.1.5 if there is some sort of regression involved. But given the diagnostic is backward compatible any reported issue is going to have to be replicated on the latest before being addressed in an issue.

**Comment by nemonster** [comment] 2020-05-18 15:09
And as far as the request to specifically sanitize the request body in a slow log, that's an entirely separate issue from a failure to process. It's one thing to search for an instance that can be anywhere and replace it generically. It's something else to look in a specific spot for a specific thing that may or may not be there.

And it actually is possible to do a regex that would find the source[ ...content] for a set of slow logs and replace them with blanks. It could potentially be slow, but it's going to be potentially slow no matter what you do.

**Comment by nemonster** [comment] 2020-06-16 18:01
@Leaf-Lin I've made a few changes to the sanitization utility that may impact this particular case. In the next release you'll be able to restrict the processing of a particular token to a file pattern. In addition you can flag a file type to be removed from the sanitized archive altogether. So if you wanted to simply take the slow logs out of the sanitized diag that should be easy to do. Or you can process it and remove just the query between the brackets. There will be an example of that in the scrub.yml.

Again, as far as their tokens not being removed from the slow log, I'd need more information on the manifestation of the issue in the newest release.

**Closed** 2020-06-16 18:45 UTC
Labels: [zube]: analyzer/diagnostic
