### ISSUE TITLE
Collect systemd manifests for OS limits

### ISSUE THREAD

**Issue by eedugon** [elastic/support-diagnostics#212] opened 2018-07-23 12:07 UTC
Hi!

In some installations, limits.conf information can be overriden by systemd manifest file, so it would be great if we could collect the following files from the diagnostic tool whenever they exist:

- /usr/lib/systemd/system/elasticsearch.service --> Default file. User shouldn't touch it but it would be good to get it just in case.
- /etc/systemd/system/elasticsearch.service.d/override.conf --> This is the file that the user should configure if they want to modify the settings.

[And for sysv systems]:
- /etc/default/elasticsearch
- /etc/sysconfig/elasticsearch

A report with the content of all these files (or comments like `Not found` for files that don't exist) would be great.

Regards!
Edu

**Comment by CBlaisure** [comment] 2019-06-20 15:34
This is by design (security) as we shouldn't be collecting system files. Closing this issue.

**Closed** 2019-06-20 15:34 UTC
Labels: Retired, [zube]: Backlog, enhancement
