### ISSUE TITLE
Invalid cookie header "Set-Cookie: AWSALB=xxxxxxxxxxxx; Expires=Fri, 21 Dec 2018 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:23 GMT

### ISSUE THREAD

**Issue by priyaprabhakar777** [elastic/support-diagnostics#233] opened 2018-12-14 09:53 UTC
Getting the error 
Invalid cookie header "Set-Cookie: AWSALB=xxxxxxxxxxxx; Expires=Fri, 21 Dec 2018 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:23 GMT
==========
We execute below

wget https://github.com/elastic/support-diagnostics/releases/download/6.4.4/support-diagnostics-6.4.4-dist.zip
cd support-diagnostics-6.4.4
./diagnostics.sh --host $ES_ENDPOINT -u $USERNAME -p --ssl

**Comment by priyaprabhakar777** [comment] 2018-12-14 09:55
More details on error
---------
17:19:24 WARN  Invalid cookie header: "Set-Cookie: AWSALB=xxxxxxxxxx; Expires=Fri, 21 Dec 2018 09:19:23 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:23 GMT
17:19:24 INFO  Checking for diagnostic version updates.
17:19:24 INFO  Currently running query: _alias?pretty
17:19:24 WARN  Invalid cookie header: "Set-Cookie: AWSALB=xxxxxxxxxx; Expires=Fri, 21 Dec 2018 09:19:24 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:24 GMT
17:19:24 INFO  Currently running query: _cat/allocation?v
17:19:25 WARN  Invalid cookie header: "Set-Cookie: AWSALB=xxxxxxxxxx; Expires=Fri, 21 Dec 2018 09:19:24 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:24 GMT
17:19:25 INFO  Currently running query: _cat/master?format=json
17:19:26 WARN  Invalid cookie header: "Set-Cookie: AWSALB=xxxxxxxxxx; Expires=Fri, 21 Dec 2018 09:19:25 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:25 GMT
17:19:26 INFO  Currently running query: _cat/nodes?v&h=ip,heap.percent,ram.percent,cpu,load_1m,load_5m,load_15m,node.role,master,name,nodeId,diskAvail
17:19:27 WARN  Invalid cookie header: "Set-Cookie: AWSALB=xxxxxxxxxx; Expires=Fri, 21 Dec 2018 09:19:26 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:26 GMT
17:19:27 INFO  Currently running query: _cat/indices?v
17:19:28 WARN  Invalid cookie header: "Set-Cookie: AWSALB=xxxxxxxxxx; Expires=Fri, 21 Dec 2018 09:19:27 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:27 GMT
17:19:28 INFO  Currently running query: _cat/segments?v
17:19:31 WARN  Invalid cookie header: "Set-Cookie: AWSALB=xxxxxxxxxx; Expires=Fri, 21 Dec 2018 09:19:28 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:28 GMT
17:19:32 INFO  Currently running query: _cat/health?v
17:19:32 WARN  Invalid cookie header: "Set-Cookie: AWSALB=xxxxxxxxxx; Expires=Fri, 21 Dec 2018 09:19:32 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:32 GMT
17:19:32 INFO  Currently running query: _cat/pending_tasks?v
17:19:32 WARN  Invalid cookie header: "Set-Cookie: AWSALB=xxxxxxxxxx; Expires=Fri, 21 Dec 2018 09:19:32 GMT; Path=/". Invalid 'expires' attribute: Fri, 21 Dec 2018 09:19:32 GMT
17:19:32 INFO  Currently running query: _cat/aliases?v

**Comment by jakommo** [comment] 2018-12-14 10:22
@priyaprabhakar777 it looks like you are running this against an load balancer and the LB is complaining about headers.
Can you run it against an Elasticsearch node directly, without an LB in between?

**Comment by jakommo** [comment] 2018-12-17 08:35
> I was able to do this before without any issue. This issue suddenly pop-up

Maybe something on the LB changed? 

Anyway, can you try running it against a node directly and report back if that works?

**Comment by nemonster** [comment] 2019-01-10 18:59
Closing for now since there's not enough information to further investigate

**Comment by ZiluckMichael** [comment] 2019-07-26 01:00
If anyone else runs into this problem, it is most likely caused by which standard you use for parsing/validating Cookies. Some popular and modern HTTP clients still use RFC 2965, RFC 2109 or Netscape to validate Cookies. The one I had an issue with was Apache's HttpClient. Here's what I did to fix it in that specific instance:
```java
HttpClient httpClient = HttpClients.custom()
        .setDefaultRequestConfig(RequestConfig.custom()
                .setCookieSpec(CookieSpecs.STANDARD).build())
        .build();
```
Hope this helps someone fix their problem so they don't spend over an hour trying to figure out what's wrong.

Sources:

- https://stackoverflow.com/questions/36473478/
- https://hc.apache.org/httpcomponents-client-ga/tutorial/html/statemgmt.html
- https://tools.ietf.org/rfc/index

**Closed** 2019-08-05 21:24 UTC
Labels: [zube]: Inbox, can't reproduce

**Comment by navneetsinghpatel** [comment] 2022-09-13 12:04
> If anyone else runs into this problem, it is most likely caused by which standard you use for parsing/validating Cookies. Some popular and modern HTTP clients still use RFC 2965, RFC 2109 or Netscape to validate Cookies. The one I had an issue with was Apache's HttpClient. Here's what I did to fix it in that specific instance:
> 
> ```java
> HttpClient httpClient = HttpClients.custom()
>         .setDefaultRequestConfig(RequestConfig.custom()
>                 .setCookieSpec(CookieSpecs.STANDARD).build())
>         .build();
> ```
> 
> Hope this helps someone fix their problem so they don't spend over an hour trying to figure out what's wrong.
> 
> Sources:
> 
> * https://stackoverflow.com/questions/36473478/
> * https://hc.apache.org/httpcomponents-client-ga/tutorial/html/statemgmt.html
> * https://tools.ietf.org/rfc/index

This doesn't fix the problem but causes another. After adding the suggested code It start giving 403 for all API Calls.
`Caused by: org.springframework.web.client.HttpClientErrorException$Forbidden: 
403 Forbidden: [
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>403 Forbidden</title>
  <style t... (1019 bytes)]`
